// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

import { LogLevel } from 'angular-auth-oidc-client';

export const environment = {
  production: false,
  paginationDefault: 10,
  organizationName: 'Test',
  organizationNameMalayalam: 'സുപ്ര പസഫിക്',
  isPDCEnabled: true,//set this true to enable pdc in ledger
  API: {
    authBaseURL: 'https://ibauthstg.geovpl.in:51443/',
    apiBaseURL: 'https://ibtesting.icrats.in/',
    login: '/authorize/Account/Login',
    getLoans: 'api/loan/api/Loan/GetLedgers',
    getLoanDetails: 'api/loan/api/Loan/GetApplication',
    getCustomerDetails: 'api/customers/api/Customer/GetCustomerByID',
    getLoanReciepts: 'api/loan/api/Loan/GetLoanReceiptHistory',
    getGrouploanIndividualTransactionHistory: 'api/grouploan/api/GroupLoan/GetTransactionHistory',
    getApplications: 'api/loan/api/v2.0/Loan/GetApplications',
    getActiveLoanSchemes:
      'api/loan/api/LoanScheme/GetActiveLoanSchemes?moduleCode=VEH',
    getCustomers: 'api/customers/api/Customer/GetCustomers',
    getInstDues: 'api/loan/api/Loan/GetInstallmentInfo',
    getLoansSchemes: 'api/loan/api/LoanScheme/GetPagedLoanSchemes',
    getVehLoanReports: 'api/reports/api/Report/GetReportModules',
    getReportParameters: 'api/reports/api/Report/GetReportParametersById',
    getReportForId: 'api/reports/api/Report/GetReport',
    getReportForId2: 'api/reports/api/v2.0/Report/GetReport',
    getReportForId3: 'api/reports/api/v2.0/Report/GetReport',
    exportReportById: 'api/reports/api/Report/ExportReport',
    getAchiveSchemeList: '/api/loan/api/LoanScheme/GetActiveLoanSchemes',
    getManufacturersList: '/api/loan/api/Vechicle/GetManufacturers',
    getDealersList: '/api/loan/api/Vechicle/GetDealers',
    getModelsList: '/api/loan/api/Vechicle/GetModels',
    getCustomSearchText: '/api/loan/api/Loan/CommonSearch',
    getDealerBranches: '/api/loan/api/Vechicle/GetDealerBranches',
    getModels: '/api/loan/api/Vechicle/GetModels',
    getFuelTypes: '/api/loan/api/Vechicle/GetFuelTypes',
    getVariant: '/api/loan/api/Vechicle/GetVariants',
    getKYCDocuments: '/api/customers/api/Customer/GetKYCDocumentTypes',
    getCompanyDetails: '/api/customers/api/General/GetCompanyInfo',
    getMenu: 'api/customers/api/v2.0/General/GetMenu',
    getCurrentUser: '/api/customers/api/General/GetCurrentUserInfo',
    setCurrentBranch: '/api/customers/api/General/SetCurrentBranch',
    getCustomerCreditScoreHistory:
      'api/customers/api/Customer/GetCreditScoreHistory',
    getCustomerLoanHistory: 'api/customers/api/Customer/GetLoanHistory',
    getCustomerVerificationHistory:
      'api/customers/api/Customer/GetVerificationHistory',
    getCustomerKycDocuments: 'api/customers/api/Customer/GetKYCDocuments',
    getApplicationFees: 'api/loan/api/LoanScheme/GetApplicationFees',
    getInterestRate: 'api/loan/api/LoanScheme/GetInterestRate',
    getActualAndFlatInterestRate: 'api/loan/api/LoanScheme/GetActualAndFlatInterestRate',
    getEquatedInstallmentInfo: 'api/loan/api/Loan/GetEquatedInstallmentInfo',
    getLoanSchedules: 'api/loan/api/Loan/GetLoanSchedules',
    getAttachmentTypes: 'api/loan/api/LoanScheme/GetAttachmentTypes',
    createVehApplication: 'api/loan/api/Loan/SaveApplication',
    updateVehApplication: 'api/loan/api/Loan/SaveApplication',
    submitTvrCheck: 'api/loan/api/Loan/SaveVarificationDetails',
    getApprovalInfo: 'api/loan/api/Loan/GetLoanApplicationApprovalInfo',
    SaveApprovalDetails: 'api/loan/api/Loan/SaveApprovalDetails',
    getBranches: 'api/customers/api/General/GetBranches',
    GetAllBranchContacts: 'api/customers/api/General/GetAllBranchContacts',
    getAssociateBranchByHeadID:
      'api/finance/api/Finance/GetAssociateBranchByHeadID',
    getFileById: 'api/general/api/General/GetFileByID',
    updateLoanApplication: 'api/loan/api/Loan/UpdateApplication',
    getAttachements: 'api/loan/api/Loan/GetLoanAttachments',
    saveAttachment: 'api/loan/api/Loan/SaveLoanAttachment',
    getAppliedLoanFees: 'api/loan/api/Loan/GetAppliedLoanFees',
    saveApplicationAppliedLoanFees:
      'api/loan/api/Loan/SaveApplicationAppliedLoanFees',
    PrintVoucher2: 'api/finance/api/Voucher/PrintVoucher2',
    PrintMultipleVoucher: 'api/finance/api/Voucher/PrintMultipleVoucher',

    GetCustomerProfileSummary:
      'api/customers/api/Customer/GetCustomerProfileSummary',
    creditCheck: 'api/loan/api/Loan/GetCreditScoreVerification',
    creditDetails: 'api/customers/api/Customer/GetCreditScoreReport',
    saveCreditScore: 'api/loan/api/Loan/SaveCIRVerification',
    creditReportDetails: 'api/customers/api/Customer/GetCreditReportLoans',
    verificationStatus: 'api/loan/api/Loan/GetVerifiedInfo',
    getActiveMarketingExecutives: 'api/customers/api/General/GetActiveMarketingExecutives',
    getInsuranceCompanies: `api/customers/api/General/GetInsuranceCompanies`,
    getLoanFeeStructure: 'api/loan/api/LoanScheme/GetApplicationFees',
    getAvailableInstDates: 'api/loan/api/Loan/GetAvailableInstallmentDates',
    getAccounts: 'api/finance/api/Finance/GetAccountHeads',
    saveDisbursement: 'api/loan/api/Loan/SaveDisbursementDetails',
    getStates: 'api/customers/api/General/GetStates',
    getNationalities: 'api/customers/api/General/GetNationalities',
    getCountries: 'api/customers/api/General/GetCountries',
    getNonIndividualEntityTypes:
      'api/customers/api/General/GetNonIndividualEntityTypes',
    getProfessions: 'api/customers/api/General/GetProfessions',
    getIncomeRanges: 'api/customers/api/General/GetIncomeRanges',
    getGeneralSettings: 'api/general/api/General/GetGeneralSettings',
    getLocalBodyTypes: 'api/customers/api/General/GetLocalBodyTypes',
    getDistricts: 'api/customers/api/General/GetDistricts',
    getTehsils: 'api/customers/api/General/GetTehsils',
    getPostOffices: 'api/customers/api/General/GetPostOffices',
    saveReceipt: 'api/loan/api/Loan/SaveReceipt',
    getVillages: 'api/customers/api/General/GetVillages',
    getLocalBodies: 'api/customers/api/General/GetLocalBodies',
    getBankAddress: 'api/customers/api/General/GetBankAddress',
    getAccClosingDues: 'api/loan/api/Loan/GetAccountClosingDues',
    closeLoan: 'api/loan/api/Loan/SaveAccountClosing',
    getMatchedCustomers: 'api/customers/api/Customer/GetMatchedCustomers',
    postCustomer: 'api/customers/api/Customer/PostCustomer',
    saveDiscount: 'api/loan/api/Loan/SaveLoanDiscountRequest',
    getDiscount: 'api/loan/api/Loan/GetLoanDiscountDetails',
    approveOrRejectDiscount: 'api/loan/api/Loan/SaveLoanDiscountApproval',
    getRecoveryStatus: 'api/loan/api/Loan/GetAllRecoveryStatus',
    saveRecoveryStatus: 'api/loan/api/Loan/SaveRecoveryStatus',
    getAllRecoverySteps: 'api/loan/api/Loan/GetAllRecoverySteps',
    deleteLastRecoveryStatus: 'api/loan/api/Loan/DeleteLastRecoveryStatus',
    getLoanPaySchedule: 'api/loan/api/Loan/GetPaymentHistory',
    verification: 'api/loan/api/Loan/SaveVarificationDetails',
    saveCreditVerification: 'api/loan/api/Loan/SaveCIRVerification',
    GetLoanSchemeByName: 'api/loan/api/LoanScheme/GetLoanSchemeByName',
    GetCibilAccountTypes: 'api/customers/api/General/GetCibilAccountTypes',
    saveLoanScheme: 'api/loan/api/LoanScheme/SaveLoanScheme',
    GetLoanAttachmentTypes: 'api/loan/api/Loan/GetLoanAttachmentTypes',
    GetLiabilities: 'api/customers/api/Customer/GetCurrentCustomerLiability',
    GetCustomerProfession: 'api/customers/api/General/GetProfessions',
    getCustomerDetailsV2: 'api/customers/api/v2.0/Customer/GetCustomerByID',
    GetAccountHeads: 'api/finance/api/Finance/GetAccountHeads',
    GetTaxes: 'api/finance/api/Finance/GetTaxes',
    DeleteLoanApplication: 'api/loan/api/Loan/DeleteLoanApplication',
    GetInstallmentWiseDue: 'api/loan/api/Loan/GetInstallmentWiseDue',
    GetOtherChargeDueWithTax: 'api/loan/api/Loan/GetOtherChargeDueWithTax',
    GetOtherChargeDueWithTaxAndDiscount:
      'api/loan/api/Loan/GetOtherChargeDueWithTaxAndDiscount',
    GetOtherCharges: 'api/finance/api/Finance/GetOtherCharges',
    AddOtherChargesList: 'api/finance/api/Finance/PostOtherCharge',
    DeleteOtherCharge: 'api/finance/api/Finance/DeleteOtherCharge',
    AddVehicleDetails: 'api/loan/api/Loan/UpdateVehicleDetails',
    GetFlagReasons: 'api/customers/api/Customer/GetFlagReasons',
    GetImageBytesByID: 'api/customers/api/General/GetImageBytesByID',
    DeleteReceipt: 'api/loan/api/Loan/DeleteReceipt',
    DeleteGroupLoanReceipt: 'api/grouploan/api/GroupLoan/DeleteReceipt',
    getLoanApplicationApprovalInfo: 'api/grouploan/api/GroupLoan/GetLoanApplicationApprovalInfo',



    GetInstallmentTranHistory: '/api/loan/api/Loan/GetInstallmentTranHistory',
    getSubAccounts: 'api/finance/api/Finance/GetSubAccounts',
    GetDisbursementInfo: 'api/loan/api/Loan/GetLoanApplicationDisbursementInfo',
    getApplicationFeesByScheme:
      'api/loan/api/LoanScheme/GetApplicationFeesWithTaxes',
    getApplicationFeesByLoanAppNum:
      'api/loan/api/Loan/GetApplicationFeesByLoanAppNumber',
    getAccountHeadByID: 'api/finance/api/Finance/GetAccountHeadByID',
    getActiveCollectionExecutives:
      'api/customers/api/General/GetActiveCollectionExecutives',
    getActivegenCollectionExecutives:
      'api/general/api/Executive/GetActiveCollectionExecutives',
    getActiveRelationshipExecutives:
      'api/customers/api/General/GetActiveRelationshipExecutives',
    getSaveCollectionCategory:
      'api/loan/api/Loan/SaveCollectionCategory',
    getActivegenMarketingExecutive:
      'api/general/api/Executive/GetActiveMarketingExecutives',
    getLoanDiscountableItems: 'api/loan/api/Loan/GetLoanDiscountableItems',
    getLoanModule: 'api/loan/api/Loan/GetLoanModule',
    getCurrentUserRoles: 'api/general/api/User/GetCurrentUserRoles',
    deleteLoanLedger: 'api/loan/api/loan/DeleteLoanLedger',
    getItemModel: 'api/loan/api/Vechicle/GetItemModel',
    getModelsByManufacturerType:
      'api/loan/api/Vechicle/GetModelsByManufacturerType',
    getDealer: 'api/loan/api/Vechicle/GetDealer',
    saveItemModel: 'api/loan/api/Vechicle/SaveItemModel',
    saveDealer: 'api/loan/api/Vechicle/SaveDealer',
    getPagedDealers: 'api/loan/api/Vechicle/getPagedDealers',
    getLoanConfiguration: 'api/loan/api/LoanScheme/GetLoanConfiguration',
    getLoanPledgeConfig: 'api/loan/api/Pledge/GetLoanPledgeConfig',
    getOrnamentList: 'api/gl/api/Ornament/GetOrnamentList',
    getLoanSettings: 'api/loan/api/Loan/GetLoanSettings',
    getSalutations: 'api/general/api/General/GetSalutations',
    getLedgers: '/api/loan/api/v2.0/Loan/CommonSearch',

    getFinancialAuditList: 'api/loan/recovery/api/Audit/GetTrialBalance',
    getFinancialAuditDetails: 'api/loan/recovery/api/Audit/GetLedgerReport',
    UpdateAuditResponse: 'api/loan/recovery/api/Audit/UpdateAuditResponse',
    GetAuditResponse: 'api/loan/recovery/api/Audit/GetAuditResponse',
    SyncTrialBalance: 'api/loan/recovery/api/Audit/SyncTrialBalance',



    saveCustomerKYCRequest: 'api/customers/api/Customer/SaveCustomerKYCRequest',
    rejectCustomerKyc: 'api/customers/api/Customer/RejectCustomerKyc',
    approveCustomerKyc: 'api/customers/api/Customer/ApproveCustomerKyc',

    getManufacturersByScheme: '/api/loan/api/Vechicle/GetManufacturersByScheme',
    GetManufacturersByVehicleType: '/api/loan/api/Vechicle/GetManufacturersByVehicleType',
    getVehicleTypes: '/api/loan/api/Vechicle/GetVehicleTypes',
    lockApplication: '/api/loan/api/loan/LockApplication',
    unlockApplication: '/api/loan/api/loan/UnlockApplication',
    getUsers: 'api/general/api/User/GetUsers',

    getAuditTypeList: 'api/loan/recovery/api/Audit/GetAuditTypeFrequency',
    saveAuditType: 'api/loan/recovery/api/Audit/InsertAuditTypeFrequency',


    getAuditor: 'api/loan/recovery/api/Audit/GetAuditors',
    getBranchWiseAuditors: 'api/loan/recovery/api/Audit/GetBranchWiseAuditors',
    saveAuditSchedule: 'api/loan/recovery/api/Audit/InsertAuditSchedule',
    getAuditSchedule: 'api/loan/recovery/api/Audit/GetAuditSchedule',

    saveAuditChecklistTemplate: 'api/loan/recovery/api/Audit/InsertCheckListTemplate',
    getAuditChecklistTemplate: 'api/loan/recovery/api/Audit/GetCheckListTemplate',
    saveChecklistItem: 'api/loan/recovery/api/Audit/InsertChecklistItem',
    getChecklistItem: 'api/loan/recovery/api/Audit/GetCheckListItems',

    updateAuditCheckListItems: 'api/loan/recovery/api/Audit/UpdateAuditCheckListItems',
    getAuditCheckList: 'api/loan/recovery/api/Audit/GetAuditCheckList',

    completeAudit: 'api/loan/recovery/api/Audit/CompleteAudit',
    getAuditReport: 'api/loan/recovery/api/Audit/GetAuditReport',

    GetBeneficiaryAccounts: '/api/customers/api/Customer/GetBeneficiaryAccounts',
    GetApplicationStageLogsByID: 'api/loan/api/Loan/GetApplicationStageLogsByID',
    GetRelations: '/api/customers/api/General/GetRelations',


    getGPLedgersCommonSearch: 'api/grouploan/api/GroupLoan/CommonSearch',
    getGPLedgers: 'api/grouploan/api/GroupLoan/GetLedgers',
    getGPApplications: 'api/grouploan/api/grouploan/GetApplications',
    getGPApplication: 'api/grouploan/api/GroupLoan/GetApplication',
    getGPLoanVerificationInfo: 'api/grouploan/api/GroupLoan/GetLoanApplicationVerificationInfo',
    SaveVarificationDetails: 'api/grouploan/api/GroupLoan/SaveVarificationDetails',




    getAllSchemes: 'api/grouploan/api/LoanScheme/GetAllLoanSchemes',
    GetAllGroupCentres: 'api/grouploan/api/GroupCentre/GetAllGroupCentres',
    GetHouseTypes: 'api/general/api/General/GetHouseTypes',
    GetHouseRoofTypes: 'api/general/api/General/GetHouseRoofTypes',
    CustomerPreCheckValidation: 'api/grouploan/api/GroupLoan/CustomerPreCheckValidation',
    GetGroupLoanConfiguration: 'api/grouploan/api/LoanScheme/GetGroupLoanConfiguration',
    getGroupLoanInterestRate: 'api/grouploan/api/LoanScheme/GetInterestRate',


    getVehicleTypesByManufacturer: '/api/loan/api/Vechicle/GetVehicleTypesByManufacturer',
    getCreditBaseTypes: 'api/loan/api/Loan/GetCreditBaseTypes',
    getAuditReportData: 'api/loan/recovery/api/Audit/GetAuditReportData',

    getLoanRecoveryList: 'api/loan/recovery/api/LoanRecovery/GetRecentCustomers',
    saveLoanAction: 'api/loan/recovery/api/LoanRecovery/SaveLoanActionData',
    getLoanActionList: 'api/loan/recovery/api/LoanRecovery/GetLoanActions',
    updateLoanAction: 'api/loan/recovery/api/LoanRecovery/UpdateLoanAction',
    getMarketingExicutive: 'api/general/api/Executive/GetActiveMarketingExecutives',
    getRelationshipExicutive: 'api/general/api/Executive/GetActiveRelationshipExecutives',
    GetLastRefreshOn: 'api/customers/api/General/GetLastRefreshOn',

    getTDAccountDetails: 'api/deposit/api/Deposit/GetTDAccountDetails',
    getDepositHolders: 'api/deposit/api/Deposit/GetDepositHolders',
    addDepositor: 'api/deposit/api/Deposit/AddAdditionalDepositor',
    updateTDEffectiveDate: 'api/deposit/api/Deposit/UpdateTDEffectiveDate',
    updateDepositModeOfOperation: 'api/deposit/api/Deposit/UpdateDepositModeOfOperation',
    getVehicleLoanHistory: 'api/loan/api/Loan/GetVehicleLoanHistory',
    getApplicationInfo: 'api/deposit/api/Deposit/GetApplicationInfo',
    addAdditionalApplicant: 'api/deposit/api/Deposit/AddAdditionalApplicant',
    getManufacturer: 'api/loan/api/Vechicle/GetManufacturer',
    saveManufacturer: 'api/loan/api/Vechicle/SaveManufacturer',
    getManufacturers: 'api/loan/api/Vechicle/GetPagedManufacturers',
    getTATransAccountDetails: 'api/deposit/api/Deposit/GetTAAccountTransactionDetails',
    sbUnlockTransaction: 'api/deposit/api/Deposit/SBUnlockTransaction',
    GetAllDepositSchemes: 'api/deposit/api/DepositScheme/GetAllDepositSchemes',
    isValidTransactionalAccount: 'api/deposit/api/Deposit/IsValidTransactionalAccount',
    getTransactionalAccounts: 'api/deposit/api/Deposit/GetTransactionalAccounts',
    generateAdminConfigAccessOTP: 'api/general/api/AdminConfig/GenerateAdminConfigAccessOTP',
    verifyAdminConfigAccessOTP: 'api/general/api/AdminConfig/VerifyAdminConfigAccessOTP',
    rejectApplication: 'api/loan/api/Loan/RejectApplication',
    getModelsByManufacturerVehicleType: '/api/loan/api/Vechicle/GetModelsByManufacturerVehicleType',
    GetInstallmentWiseDueWithTaxAndDiscount: 'api/loan/api/Loan/GetInstallmentWiseDueWithTaxAndDiscount',
    getGPLedger: 'api/grouploan/api/GroupLoan/GetLedger',
    getLoanDisbursementTransactionInfo: 'api/grouploan/api/GroupLoan/GetLoanDisbursementTransactionInfo',
    GetGeolocationDescription: 'api/general/api/General/GetGeolocationDescription',
    getGrouploanEquatedInstallmentInfo: 'api/grouploan/api/GroupLoan/GetEquatedInstallmentInfo',
    DeleteLoanAttachment: 'api/loan/api/Loan/DeleteLoanAttachment',
    getGrouploanApplicationDetails: 'api/grouploan/api/GroupLoan/GetApplication',
    SaveGrouploanApplication: 'api/grouploan/api/GroupLoan/SaveApplication',
    GetGroupLoanReceiptHistory: 'api/grouploan/api/GroupLoan/GetGroupLoanReceiptHistory',
    GetVoucherInfo: 'api/grouploan/api/GroupLoan/GetVoucherInfo',

    updateGroupLoanApplication: 'api/grouploan/api/GroupLoan/UpdateApplication',
    ChangeLoanSchedules: 'api/loan/api/Loan/ChangeLoanSchedules',
    postEntity: 'api/customers/api/Customer/PostEntity',
    getEntityDetailsV2: 'api/customers/api/v2.0/Customer/GetCustomerByID',
    getRelationshipControlTypes: 'api/customers/api/general/GetRelationshipControlTypes',
    saveEntityKYCRequest: 'api/customers/api/Customer/SaveCustomerKYCRequest',
    approveEntityKyc: 'api/customers/api/Customer/ApproveEntityKyc',

    getLoanActionTypes: 'api/loan/recovery/api/LoanRecovery/GetLoanActionTypes',
    updateNoticePrintDate: 'api/loan/recovery/api/LoanRecovery/UpdateNoticePrintDate',

    getCustomerNameByPAN: 'api/customers/api/Customer/GetCustomerNameByPAN',
    getCustomerNameByAadhaarNumber: 'api/customers/api/Customer/GetCustomerNameByAadhaarNumber',
    createPrecheckDeviationRequest: 'api/grouploan/api/GroupLoan/CreatePrecheckDeviationRequest',
    getPrecheckDeviationRequests: 'api/grouploan/api/GroupLoan/GetPrecheckDeviationRequests',
    saveDeviationApprovalDetails: 'api/grouploan/api/GroupLoan/SaveDeviationApprovalDetails',
    GetLoanSchemeBranches: 'api/loan/api/LoanScheme/GetLoanSchemeBranches',
    GetReceiptStaticQRCodeString: 'api/finance/api/QRCodePay/GetStaticQRCode',
    GetLoanDisbursementDetails: 'api/loan/api/Loan/GetLoanDisbursementDetails',
    getAllbranchContacts: 'api/general/api/General/GetAllBranchContacts',
    getPostOffice: 'api/general/api/General/GetPostOffice',
    savePostOffice: 'api/general/api/General/SavePostOffice',
    getPagedPostOffices: 'api/general/api/General/GetPagedPostOffices',
    bulkImportReceiptTransactions: 'api/loan/api/Loan/BulkImportReceiptTransactions',
    getMultipleReceiptTaxes: 'api/loan/api/Loan/GetMultipleReceiptTaxes',
    deleteGroupLoanLedger: 'api/grouploan/api/GroupLoan/DeleteLoanLedger',
    getMyCollectionLedgers: 'api/grouploan/api/GroupLoan/GetMyCollectionLedgers',
    getExecutiveList: 'api/general/api/Executive/GetExecutives',
    saveExecutive: 'api/general/api/Executive/SaveExecutive',
    updateExecutive: 'api/general/api/Executive/UpdateExecutive',
    getLawyers: 'api/loan/recovery/api/LoanRecovery/GetLawyers',
    getTeleCallers: 'api/loan/recovery/api/LoanRecovery/GetTeleCallers',
    getTransactionVerificationList: 'api/grouploan/api/GroupLoan/GetTransactionVerificationList',
    saveTransactionVerification: 'api/grouploan/api/GroupLoan/SaveTransactionVerification',
    getBorrowerInstallmentInfo: 'api/grouploan/api/GroupLoan/GetBorrowerInstallmentInfo',
    getCustomerImage: 'api/customers/api/Customer/GetCustomerImage',
    getAllCheques: 'api/finance/api/Finance/GetAllCheques',
    updateCheque: 'api/finance/api/Finance/UpdateCheque',
    mapCheque: 'api/finance/api/Finance/MapCheque',
    deleteCheque: 'api/finance/api/Finance/DeleteCheque',
    getChequeStatus: 'api/finance/api/Finance/GetChequeStatus',
    getLedger: 'api/loan/api/Loan/GetLedger',
    getRejectReasons: 'api/general/api/General/GetRejectReasons',
    getLatestBulkImportReceiptRequest: 'api/loan/api/Loan/GetLatestBulkImportReceiptRequest',
    getBusinessSources: 'api/general/api/General/GetBusinessSources',
    getActiveExecutives: 'api/general/api/Executive/GetActiveExecutives',
    groupLoanSaveReceipt: 'api/grouploan/api/GroupLoan/SaveReceipt',
    getBorrowerOtherCharges: 'api/grouploan/api/GroupLoan/GetBorrowerOtherCharges',
    saveBorrowerOtherCharge: 'api/grouploan/api/GroupLoan/SaveBorrowerOtherCharge',
    deleteBorrowerOtherCharge: 'api/grouploan/api/GroupLoan/DeleteBorrowerOtherCharge',

    getBankIfsc: 'api/general/api/General/GetBankIfsc',
    saveBankIfsc: 'api/general/api/General/SaveBankIfsc',
    getBankIfscs: 'api/general/api/General/GetBankIfscs',
    getCustomerEditHistory: 'api/customers/api/Customer/GetCustomerEditHistory',
    recoveryNoticePrint: 'api/loan/recovery/api/LoanRecovery/PrintNotice',
    recoveryLabelPrint: 'api/loan/recovery/api/LoanRecovery/PrintLabel',
    getReportID: 'api/reports/api/Report/GetReportId',
    getCreditBaseDocTypes: 'api/loan/api/Loan/GetCreditBaseDocTypes',
    getActiveBankAccounts: 'api/finance/api/DirectPay/GetActiveBankAccounts',
    getActiveFIExecutives: 'api/customers/api/General/GetActiveFieldInspectionExecutives',
    assignLoanFIExecutive: 'api/loan/api/Loan/AssignLoanFIExecutive',
    bulkImportVoucher: 'api/finance/api/Voucher/BulkImportVoucher',
    getLastFiveBulkImportVoucherLogs: 'api/finance/api/Voucher/GetLastFiveBulkImportVoucherLogs',
    getLatestBulkImportVoucherLogFile: 'api/finance/api/Voucher/GetLatestBulkImportVoucherLogFile',

    getLatestBulkImportVoucherRequestInfo: 'api/finance/api/Voucher/GetLatestBulkImportVoucherRequestInfo',
    getDepoApplicationInfo: 'api/deposit/api/Deposit/GetDepoApplicationInfo',
    updateDepoApplicationFields: 'api/deposit/api/Deposit/UpdateDepoApplicationFields',
    sendSMSConfirmation: 'api/customers/api/Customer/SendSMSConfirmation',
    verifyPhoneNumberOTP: 'api/customers/api/Customer/VerifyPhoneNumberOTP',
    getAuditExcelReport: 'api/loan/recovery/api/Audit/DownloadAuditReport',
    getInterestIntervalTypes: 'api/deposit/api/DepositScheme/GetInterestIntervalTypes',
    getMappedPolicy: 'api/loan/api/Insurance/GetMappedPolicy',
    savePolicy: 'api/loan/api/Insurance/SavePolicy',
    removeMappedPolicy: 'api/loan/api/Insurance/RemoveMappedPolicy',
    getInsurancPolicyTypes: 'api/general/api/Insurance/GetInsurancPolicyTypes',
    getGoldAuditList: 'api/loan/recovery/api/Audit/GetGoldAuditList',
    getFilteredGoldAuditList: 'api/loan/recovery/api/Audit/GetGoldAuditList1',
    updateGoldAuditCheckListItems: 'api/loan/recovery/api/Audit/GetGoldAuditList',
    getGoldAuditCheckList: 'api/loan/recovery/api/Audit/GetGoldAuditCheckList',
    saveGoldAudit: 'api/loan/recovery/api/Audit/SaveGoldAudit',
    getGoldAuditRemarks: 'api/loan/recovery/api/Audit/GetGoldAuditRemarks',
    saveGoldAuditRemarks: 'api/loan/recovery/api/Audit/SaveGoldAuditRemarks',
    savePurityAudit: 'api/loan/recovery/api/Audit/SavePurityAudit',
    saveOrUpdateAuditor: 'api/loan/recovery/api/Audit/InsertOrUpdateAuditor',
    getBranchRoleUsers: 'api/loan/recovery/api/Audit/GetBranchRoleUsers',
    saveGoldAuditRemarksReply: 'api/loan/recovery/api/Audit/SaveGoldAuditRemarksReply',
    getledgersExecutives: 'api/loan/recovery/api/LoanRecovery/GetledgersExecutives',
    addRemappedExecutives: 'api/loan/recovery/api/LoanRecovery/AddRemappedExecutives',
    getAuditPlanner: 'api/loan/recovery/api/Audit/GetAuditPlanner',

    getCibilDataInTUDFFormat: 'api/reports/api/Report/GenerateTUDFFile',
    getLoanApplicants: 'api/loan/api/Loan/GetLoanApplicants',
    saveMissingReceipt: 'api/loan/api/Loan/SaveMissingReceipt',
    getFIPendingApplications: 'api/loan/api/Loan/getFIPendingApplications',
    saveFIVerification: 'api/loan/api/Loan/SaveFIVerification',
    getSubDealers: '/api/loan/api/Vechicle/GetSubDealers',
    getSubDealer: 'api/loan/api/Vechicle/GetSubDealer',
    saveSubDealer: 'api/loan/api/Vechicle/SaveSubDealer',
    getPagedSubDealers: 'api/loan/api/Vechicle/GetPagedSubDealers',
    getUpcomingSchedule: 'api/grouploan/api/GroupLoan/GetUpcomingSchedule',
    savePromisedToPayMarking: 'api/grouploan/api/GroupLoan/SavePromisedToPayMarking',
    detachLOD: 'api/deposit/api/Deposit/DetachLOD',
    reattachLOD: 'api/deposit/api/Deposit/ReattachLOD',
    getLODView: 'api/deposit/api/Deposit/GetLODView',
    saveLoanReschedules: 'api/loan/api/Loan/SaveLoanReschedules',
    saveMultipleSchemeReschedules: 'api/loan/api/LoanScheme/SaveMultipleSchemeReschedules',
    getBucket: 'api/reports/api/Report/GetBucket',
    exportReportAsBackgroundTask: 'api/reports/api/Report/ExportReportAsBackgroundTask',
    getFile: 'api/reports/api/Report/GetFile',
    getInterestRates: 'api/loan/api/LoanScheme/GetInterestRates',
    getScheduledReport: 'api/scheduler/api/Process/GetScheduledReport',
    GetLoanExecutives: 'api/loan/api/Loan/GetLoanExecutives',
    getCollectionCategories: 'api/loan/api/Loan/GetCollectionCategories',
    UpdateLoanExecutive: 'api/loan/api/Loan/UpdateLoanExecutives',
    gettLoanPurposes: 'api/general/api/General/GetLoanPurposes',
    GetGpRelations: '/api/general/api/General/GetRelations',
    CreatePrecheckDeviationRequest: 'api/grouploan/api/GroupLoan/CreatePrecheckDeviationRequest',
    getGPCentres: 'api/grouploan/api/GroupCentre/GetGroupCentres',
    SaveGroupCentre: 'api/grouploan/api/GroupCentre/SaveGroupCentre',
    GetTaxonomyValues: 'api/general/api/General/GetTaxonomyValues',
    GetCurrentBranch: 'api/general/api/User/GetCurrentBranch',
    saveGLoanReschedules: 'api/grouploan/api/GroupLoan/SaveLoanReschedules',
    saveCentreReschedules: 'api/grouploan/api/GroupCentre/SaveCentreReschedules',
    SaveMultipleGLoanSchemeReschedules: 'api/grouploan/api/LoanScheme/SaveMultipleSchemeReschedules',
    isGoogleApiEnabled: 'api/general/api/General/IsGoogleApiEnabled',
    GetGPLoanApplicationDisbursementInfo: 'api/grouploan/api/GroupLoan/GetLoanApplicationDisbursementInfo',
    GPLoanSchemeByName: 'api/grouploan/api/LoanScheme/GetLoanSchemeByName',
    GetDocsClauses: 'api/general/api/General/GetDocsClauses',
    getLatestBulkImportTranAccountsRequestInfo: 'api/deposit/api/Deposit/GetLatestBulkImportTranAccountsRequestInfo',
    bulkImportTransactionAccountReceiptAndPayments: 'api/deposit/api/Deposit/BulkImportTransactionAccountReceiptAndPayments',
    getLatestBulkImportTransAccHoldAmountRequestInfo: 'api/deposit/api/Deposit/GetLatestBulkImportTransAccHoldAmountRequestInfo',
    bulkImportTransactionAccountHoldAmount: 'api/deposit/api/Deposit/BulkImportTransactionAccountHoldAmount',
    generateAllBranchProfitAndLossReport: 'api/finance/api/DynamicReport/GenerateAllBranchProfitAndLossReport',
    getReportStatus: 'api/finance/api/DynamicReport/GetReportStatus',
    generateBranchBalanceSheet: 'api/finance/api/DynamicReport/GenerateBalanceSheetReport',
    getAllBranchReportData: 'api/finance/api/DynamicReport/GetAllBranchReportData',
    generateAllBranchBalanceSheetReport: 'api/finance/api/DynamicReport/GenerateAllBranchBalanceSheetReport',
    groupAppliedLoanFeesByAccountNumber: 'api/grouploan/api/GroupLoan/GetAppliedLoanFeesByAccountNumber',
    resubmitReceipts: 'api/loan/api/Loan/ResubmitReceipts',
    getGeolocationDescription: 'api/general/api/General/GetGeolocationDescription',
    generateProfitAndLossReport: 'api/finance/api/DynamicReport/GenerateProfitAndLossReport',
    getReportData: 'api/finance/api/DynamicReport/GetReportData',
    getGoldGlobalLoanSettings: 'api/gl/api/GoldLoanSettings/GetGoldGlobalLoanSettings',
    GetCertificatePrint: 'api/loan/api/Print/GetCertificatePrint',
    GetLoanApplication: 'api/gl/api/GoldLoanLedger/GetLoanApplication',
    GetgoldLoanSchemeByName: 'api/gl/api/GoldLoanDefinition/GetLoanSchemeByName',
    getLatestBulkImportTranAccountsLogFile: 'api/deposit/api/Deposit/GetLatestBulkImportTranAccountsLogFile',
    getLatestBulkImportTranAccountsHoldAmtLogFile: 'api/deposit/api/Deposit/GetLatestBulkImportTranAccountsHoldAmtLogFile',
    getLatestBulkImportReceiptLogFile: 'api/loan/api/Loan/GetLatestBulkImportReceiptLogFile', 
    getCurrentGoldRate: 'api/gl/api/GoldRate/GetCurrentGoldRate',
    updateLoanSettings: 'api/loan/api/Loan/UpdateLoanSettings',
    goldInterestDue: 'api/gl/api/GoldLoanLedger/GetInterestDue',
    getLoanApprovedInfo: 'api/loan/api/Loan/GetLoanApprovedInfo',
    updateGeneralSettings: 'api/general/api/General/UpdateGeneralSettings',
    getKycConfigSettings: 'api/general/api/General/GetKycConfigSettings',
    fiVerificationReturn: 'api/loan/api/Loan/FIVerificationReturn',
    getLoanFIExecutiveInfo: 'api/loan/api/Loan/GetLoanFIExecutiveInfo',
    completeFIVerification: 'api/loan/api/Loan/CompleteFIVerification',
    getLoanFIExecutives: 'api/loan/api/Loan/GetLoanFIExecutives',
    unapproveLoanDiscount: 'api/loan/api/Loan/UnapproveLoanDiscount',

    getTUDFReportFile: 'api/reports/api/Report/GetTUDFReportFile',
    getTUDFReportStatus: 'api/reports/api/Report/GetTUDFReportStatus',
    saveLoanFreezeRequest: 'api/loan/api/Loan/SaveLoanFreezeRequest',
    getLoanFrozenDetails: 'api/loan/api/Loan/GetLoanFrozenDetails',
    insertFrozenLoan: 'api/loan/recovery/api/LoanRecovery/InsertFrozenLoan',

    generateAadhaarOTP: 'api/customers/api/Customer/GenerateAadhaarOTP',
    submitAadhaarOTP: 'api/customers/api/Customer/SubmitAadhaarOTP',
    verifyBankAccount: 'api/customers/api/Customer/VerifyBankAccount',
    isVerifiedDocument: 'api/customers/api/Customer/IsVerifiedDocument',
    verifyKYCDocuments: 'api/customers/api/Customer/VerifyKYCDocuments',
    getExternalKYCDocumentInfo: 'api/customers/api/Customer/GetExternalKYCDocumentInfo',
    externalKYCDocumentInfoVerification: 'api/customers/api/Customer/ExternalKYCDocumentInfoVerification',
    GetNoObjectionCertificatePrint: 'api/loan/api/Print/GetNoObjectionCertificatePrint',
    getLoanAppCustomerByID: 'api/loan/api/Loan/GetLoanAppCustomerByID',
    resetCKYCProfileSync: 'api/customers/api/Customer/ResetCKYCProfileSync',
    customerPreCheckValidation: 'api/loan/api/Loan/CustomerPreCheckValidation',
    getCustomerPreChecks: 'api/loan/api/Loan/GetCustomerPreChecks',
    submitKycForRepair: 'api/customers/api/Customer/SubmitKycForRepair',
    calculateDefaultChargeTaxes: 'api/loan/api/Loan/CalculateDefaultChargeTaxes',
    calculatePenalTaxes: 'api/loan/api/Loan/CalculatePenalTaxes',
    getGoldRateAsOnDate: 'api/gl/api/GoldRate/GetGoldRateAsOnDate',     
    getLatestBulkImportCustomerRequest: 'api/customers/api/Customer/GetLatestBulkImportCustomerRequest',
    getLastFiveBulkImportCustomerLogs: 'api/customers/api/Customer/GetLastFiveBulkImportCustomerLogs', 
    bulkImportCustomers: 'api/customers/api/Customer/BulkImportCustomers',
    getLatestBulkImportCustomerLogFile: 'api/customers/api/Customer/GetLatestBulkImportCustomerLogFile',
    getVoucherTemplates: 'api/finance/api/Voucher/GetVoucherTemplates',
    getVoucherTemplateDetails: 'api/finance/api/Voucher/GetVoucherTemplateDetails',
    getSubAccountsByBranch: 'api/finance/api/Finance/GetSubAccountsByBranch', 
    getMultiBranchVouchers: 'api/finance/api/Voucher/GetMultiBranchVouchers',
    saveMultiBranchIBVoucher: 'api/finance/api/Voucher/SaveMultiBranchIBVoucher',    
    getMultiBranchIBVoucherByUniqueId: 'api/finance/api/Voucher/GetMultiBranchIBVoucherByUniqueId',
    cancelMultiBranchIBVoucher: 'api/finance/api/Voucher/CancelMultiBranchIBVoucher', 
    getGoldLoanSchemeIntRateStatusSummary: 'api/gl/api/GoldLoanReport/GetGoldLoanSchemeIntRateStatusSummary',
     getFIVerifiedInfo: 'api/loan/api/Loan/GetFIVerifiedInfo',
    cancelFIVerification: 'api/loan/api/Loan/CancelFIVerification',
    updateCustomerBaseBranch: 'api/customers/api/Customer/UpdateCustomerBaseBranch',
    saveMultipleBranchWiseLoanReschedules: 'api/loan/api/Loan/SaveBranchWiseLoanReschedules',
    saveMultipleStateWiseLoanReschedules: 'api/loan/api/Loan/SaveStateWiseLoanReschedules',
    cancelCustomerKYCRequest: 'api/customers/api/Customer/CancelCustomerKYCRequest',
    getLoanUPISettings: 'api/loan/api/Loan/GetLoanUPISettings',
    getGroupLoanUPISettings: 'api/grouploan/api/GroupLoan/GetGroupLoanUPISettings',    
    getLoanSchemes: '/api/loan/api/LoanScheme/GetLoanSchemes',
  },
  ClIENT_ID: 'ibanking-client-1',
  CLIENT_SECRET: '7398095a-41da-44df-a4ff-4a9a69b99d91',
  SCOPE:
    'Customer-Read Finance-Read Reports-Read Loan-Read offline_access NBFC-GroupLoan-Read',
  // https://localhost:4200/assets/redirect.html
  //https://localhost:4200/#/login-redirect
  oicdConfig: {
    authority: 'https://isectesting.icrats.in/authorize',
    redirectUrl: 'https://localhost:4200/#/login-redirect',
    postLogoutRedirectUri: window.location.origin,
    clientId: 'nbfc-3-client',
    scope:
      'openid offline_access NBFC-Customer-Read NBFC-Finance-Read NBFC-Reports-Read NBFC-Loan-Read NBFC-GroupLoan-Read NBFC-GoldLoan-Read NBFC-Deposit-Read',
    responseType: 'code',
    silentRenew: true,
    useRefreshToken: true,
    logLevel: LogLevel.Debug,
    triggerAuthorizationResultEvent: true,
    historyCleanupOff: true,
  },
  reverseGeoCode: 'https://maps.googleapis.com/maps/api/geocode/json'
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
